export const profileText = {
  en: {
    title: "Your adventurer profile", subtitle: "Find people with time for the same adventures.", home: "Back to the world", login: "Continue with Battle.net", logout: "Sign out", loginBody: "Sign in, choose a public alias and tell us what you enjoy playing. No addon needed for interest matching.",
    notReady: "Battle.net login is not available yet. Please check back soon.", failed: "Sign-in was cancelled, expired or could not be verified. Please try again.", databaseError: "Profile storage is temporarily unavailable. Your changes have not been saved.",
    privacy: "We use your Battle.net account identifier to recognise you. No BattleTag, email, password, character history or access token is stored. The encrypted login cookie lasts up to 24 hours. Your saved profile stays until you delete it.",
    alias: "Public alias (not your BattleTag)", region: "WoW region", language: "Group language", role: "Your role", activities: "Your adventures", experience: "WoW experience", ageGroup: "Age group (optional)", timezone: "Your timezone", days: "Your regular play days", start: "From", end: "Until", schedule: "One time window for each selected day, in your timezone. End must be later on the same day; 24:00 means midnight.", adult: "I confirm I am at least 18 years old.", discoverable: "Include me in matching. Signed-in participants with a visible profile can see my alias, role, experience, shared activities and overlapping hours. My precise schedule and age group stay private.",
    save: "Save my profile", saving: "Saving...", saved: "Profile saved.", invalid: "Check your alias, activities, days and times, and confirm you are 18 or older.", sessionExpired: "Your session has expired. Sign in again before saving.",
    matches: "Your connections", empty: "No matching players yet. Your profile is ready; check back as more adventurers join.", private: "Your profile is private. Enable matching and save to find other players.", score: "interest fit", hours: "shared hours over the next 7 days", method: "An estimate, not a promise: schedule 50%, activities 30%, complementary roles 10%, experience 5%, same age group 5% when both supply it. Without age, the other weights are normalised. Same region and language required. Up to 500 participating profiles are considered, with the best 12 shown. No encounter history is used. Messaging is not available yet.",
    delete: "Delete my profile", confirmDelete: "Permanently delete my saved profile and remove me from matching.", deleted: "Your profile has been deleted and you have been signed out.", deleteError: "Deletion failed. Your profile has not been deleted; please try again.",
    names: { tank: "Tank", healer: "Healer", damage: "Damage", dungeons: "Dungeons", raids: "Raids", pvp: "PvP", questing: "Exploration & quests", collecting: "Collecting", new: "New player", returning: "Returning player", regular: "Regular player", veteran: "Long-time player", private: "Prefer not to say" } as Record<string, string>,
    weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
  },
  de: {
    title: "Dein Abenteurerprofil", subtitle: "Finde Leute mit Zeit für dieselben Abenteuer.", home: "Zurück zur Welt", login: "Mit Battle.net anmelden", logout: "Abmelden", loginBody: "Melde dich an, wähle einen öffentlichen Alias und erzähle, was du gern spielst. Für Interessen-Matching brauchst du kein Addon.",
    notReady: "Der Battle.net-Login ist noch nicht verfügbar. Schau bald wieder vorbei.", failed: "Die Anmeldung wurde abgebrochen, ist abgelaufen oder konnte nicht bestätigt werden. Bitte versuche es erneut.", databaseError: "Der Profilspeicher ist gerade nicht verfügbar. Deine Änderungen wurden nicht gespeichert.",
    privacy: "Wir erkennen dich anhand deiner Battle.net-Kontokennung. BattleTag, E-Mail, Passwort, Charakterhistorie und Zugriffstoken werden nicht gespeichert. Das verschlüsselte Login-Cookie gilt bis zu 24 Stunden. Dein gespeichertes Profil bleibt, bis du es löschst.",
    alias: "Öffentlicher Alias (nicht dein BattleTag)", region: "WoW-Region", language: "Gruppensprache", role: "Deine Rolle", activities: "Deine Abenteuer", experience: "WoW-Erfahrung", ageGroup: "Altersgruppe (freiwillig)", timezone: "Deine Zeitzone", days: "Deine regelmäßigen Spieltage", start: "Von", end: "Bis", schedule: "Ein Zeitfenster für jeden gewählten Tag, in deiner Zeitzone. Das Ende muss am selben Tag später liegen; 24:00 ist Mitternacht.", adult: "Ich bestätige, dass ich mindestens 18 Jahre alt bin.", discoverable: "Ich möchte am Matching teilnehmen. Angemeldete Teilnehmer mit sichtbarem Profil sehen meinen Alias, Rolle, Erfahrung, gemeinsame Aktivitäten und überschneidende Stunden. Genaue Spielzeiten und Altersgruppe bleiben privat.",
    save: "Profil speichern", saving: "Wird gespeichert...", saved: "Profil gespeichert.", invalid: "Prüfe Alias, Aktivitäten, Tage und Uhrzeiten und bestätige, dass du mindestens 18 bist.", sessionExpired: "Deine Sitzung ist abgelaufen. Melde dich vor dem Speichern erneut an.",
    matches: "Deine Verbindungen", empty: "Noch keine passenden Spieler. Dein Profil ist bereit; schau wieder vorbei, wenn mehr Abenteurer dabei sind.", private: "Dein Profil ist privat. Aktiviere das Matching und speichere, um andere Spieler zu finden.", score: "Interessen-Fit", hours: "gemeinsame Stunden in den nächsten 7 Tagen", method: "Eine Schätzung, kein Versprechen: Spielzeiten 50 %, Aktivitäten 30 %, ergänzende Rollen 10 %, Erfahrung 5 %, gleiche Altersgruppe 5 %, falls beide sie angeben. Ohne Altersangabe werden die übrigen Gewichte normalisiert. Gleiche Region und Sprache sind Voraussetzung. Bis zu 500 teilnehmende Profile werden berücksichtigt, die besten 12 angezeigt. Keine Begegnungshistorie. Nachrichten sind noch nicht verfügbar.",
    delete: "Profil löschen", confirmDelete: "Mein gespeichertes Profil dauerhaft löschen und mich aus dem Matching entfernen.", deleted: "Dein Profil wurde gelöscht und du wurdest abgemeldet.", deleteError: "Löschen fehlgeschlagen. Dein Profil wurde nicht gelöscht; bitte versuche es erneut.",
    names: { tank: "Tank", healer: "Heiler", damage: "Schaden", dungeons: "Dungeons", raids: "Raids", pvp: "PvP", questing: "Erkundung & Quests", collecting: "Sammeln", new: "Neueinsteiger", returning: "Wiedereinsteiger", regular: "Regelmäßiger Spieler", veteran: "Langjähriger Spieler", private: "Keine Angabe" } as Record<string, string>,
    weekdays: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
  },
};