import type { Locale } from "./config";

type SecurityText = { title: string; current: string; other: string; started: string; expires: string; revoke: string; others: string; all: string; error: string };
export const securityText: Record<Locale, SecurityText> = {
  en: { title: "Active sessions", current: "This device", other: "Other device", started: "Signed in", expires: "Expires", revoke: "Sign out", others: "Sign out other devices", all: "Sign out everywhere", error: "Sessions could not be updated. Please try again." },
  de: { title: "Aktive Sitzungen", current: "Dieses Gerät", other: "Anderes Gerät", started: "Angemeldet seit", expires: "Läuft ab", revoke: "Abmelden", others: "Andere Geräte abmelden", all: "Überall abmelden", error: "Die Sitzungen konnten nicht aktualisiert werden. Bitte erneut versuchen." },
  fr: { title: "Sessions actives", current: "Cet appareil", other: "Autre appareil", started: "Connexion", expires: "Expiration", revoke: "Déconnecter", others: "Déconnecter les autres appareils", all: "Tout déconnecter", error: "Impossible de modifier les sessions. Veuillez réessayer." },
  es: { title: "Sesiones activas", current: "Este dispositivo", other: "Otro dispositivo", started: "Inicio", expires: "Caduca", revoke: "Cerrar sesión", others: "Cerrar las otras sesiones", all: "Cerrar todas las sesiones", error: "No se pudieron actualizar las sesiones. Inténtalo de nuevo." },
  it: { title: "Sessioni attive", current: "Questo dispositivo", other: "Altro dispositivo", started: "Accesso", expires: "Scadenza", revoke: "Disconnetti", others: "Disconnetti gli altri dispositivi", all: "Disconnetti tutti", error: "Impossibile aggiornare le sessioni. Riprova." },
  pt: { title: "Sessões ativas", current: "Este dispositivo", other: "Outro dispositivo", started: "Início", expires: "Expira", revoke: "Terminar sessão", others: "Terminar as outras sessões", all: "Terminar todas as sessões", error: "Não foi possível atualizar as sessões. Tenta novamente." },
  "pt-BR": { title: "Sessões ativas", current: "Este dispositivo", other: "Outro dispositivo", started: "Início", expires: "Expira", revoke: "Sair", others: "Sair dos outros dispositivos", all: "Sair de todos os dispositivos", error: "Não foi possível atualizar as sessões. Tente novamente." },
  pl: { title: "Aktywne sesje", current: "To urządzenie", other: "Inne urządzenie", started: "Zalogowano", expires: "Wygasa", revoke: "Wyloguj", others: "Wyloguj inne urządzenia", all: "Wyloguj wszędzie", error: "Nie udało się zaktualizować sesji. Spróbuj ponownie." },
  ru: { title: "Активные сеансы", current: "Это устройство", other: "Другое устройство", started: "Вход", expires: "Истекает", revoke: "Выйти", others: "Выйти на других устройствах", all: "Выйти везде", error: "Не удалось обновить сеансы. Попробуйте ещё раз." },
};

export const sessionPrivacyText: Record<Locale, string> = {
  en: "We run Better Auth within our application; it is not an additional hosted login provider. Sessions last up to 24 hours. Our database stores the session identifier, account association, IP address, browser information and creation and expiry times for authentication and session management. You can revoke sessions in your profile; account deletion removes all sessions. Expired sessions and temporary security records are removed by daily cleanup and remain until it succeeds. Account data remains until account deletion. Request limits use keyed, pseudonymous IP or account identifiers and short-lived counters. Blizzard access and refresh tokens are not stored permanently.",
  de: "Better Auth läuft innerhalb unserer Anwendung und ist kein zusätzlicher gehosteter Login-Anbieter. Sitzungen gelten höchstens 24 Stunden. Unsere Datenbank speichert Sitzungskennung, Kontozuordnung, IP-Adresse, Browserinformationen sowie Erstellungs- und Ablaufzeit zur Anmeldung und Sitzungsverwaltung. Sitzungen kannst du im Profil widerrufen; beim Löschen des Kontos werden alle Sitzungen entfernt. Abgelaufene Sitzungen und vorübergehende Sicherheitsdaten werden täglich bereinigt und bleiben bis zur erfolgreichen Bereinigung gespeichert. Kontodaten bleiben bis zur Kontolöschung gespeichert. Anfragelimits verwenden mit einem geheimen Schlüssel pseudonymisierte IP- oder Kontokennungen und kurzlebige Zähler. Blizzard-Zugriffs- und Refresh-Tokens werden nicht dauerhaft gespeichert.",
  fr: "Better Auth fonctionne dans notre application, sans fournisseur de connexion hébergé supplémentaire. Les sessions durent au maximum 24 heures. La base conserve leur identifiant, le compte associé, l’adresse IP, les informations du navigateur et les dates de création et d’expiration pour la connexion et la gestion des sessions. Tu peux les révoquer dans ton profil ; supprimer le compte supprime toutes les sessions. Les sessions expirées et les données de sécurité temporaires sont nettoyées chaque jour et restent stockées jusqu’à la réussite du nettoyage. Les données du compte restent jusqu’à sa suppression. Les limites utilisent des identifiants IP ou de compte pseudonymisés avec une clé secrète et des compteurs temporaires. Les jetons Blizzard ne sont pas conservés durablement.",
  es: "Better Auth funciona dentro de nuestra aplicación, sin otro proveedor de acceso alojado. Las sesiones duran como máximo 24 horas. Guardamos su identificador, la cuenta asociada, IP, datos del navegador y fechas de creación y caducidad para gestionar el acceso y las sesiones. Puedes revocarlas en tu perfil; al eliminar la cuenta se eliminan todas. Las sesiones caducadas y los datos de seguridad temporales se limpian a diario y permanecen hasta que la limpieza termine correctamente. Los datos de la cuenta permanecen hasta su eliminación. Los límites usan identificadores de IP o cuenta seudonimizados con una clave secreta y contadores temporales. Los tokens de Blizzard no se guardan permanentemente.",
  it: "Better Auth funziona nella nostra applicazione, senza un ulteriore servizio di accesso ospitato. Le sessioni durano al massimo 24 ore. Il database conserva identificativo della sessione, account associato, IP, informazioni del browser e date di creazione e scadenza per gestire accesso e sessioni. Puoi revocarle nel profilo; eliminando l’account vengono rimosse tutte. Le sessioni scadute e i dati temporanei di sicurezza vengono rimossi ogni giorno e restano fino al completamento della pulizia. I dati dell’account restano fino alla sua eliminazione. I limiti usano identificativi IP o account pseudonimizzati con una chiave segreta e contatori temporanei. I token Blizzard non vengono conservati permanentemente.",
  pt: "O Better Auth funciona na nossa aplicação, sem outro fornecedor de autenticação alojado. As sessões duram até 24 horas. A base guarda o identificador da sessão, conta associada, IP, informações do navegador e datas de criação e expiração para gerir o acesso e as sessões. Podes revogá-las no perfil; eliminar a conta remove todas as sessões. As sessões expiradas e os dados temporários de segurança são limpos diariamente e permanecem até a limpeza terminar com sucesso. Os dados da conta permanecem até à sua eliminação. Os limites usam identificadores de IP ou conta pseudonimizados com uma chave secreta e contadores temporários. Os tokens Blizzard não são guardados permanentemente.",
  "pt-BR": "O Better Auth funciona dentro da nossa aplicação, sem outro provedor de autenticação hospedado. As sessões duram até 24 horas. O banco guarda identificador da sessão, conta associada, IP, informações do navegador e datas de criação e expiração para gerenciar o acesso e as sessões. Você pode revogá-las no perfil; excluir a conta remove todas as sessões. As sessões expiradas e os dados temporários de segurança são limpos diariamente e permanecem até a limpeza ser concluída com sucesso. Os dados da conta permanecem até sua exclusão. Os limites usam identificadores de IP ou conta pseudonimizados com uma chave secreta e contadores temporários. Os tokens Blizzard não são armazenados permanentemente.",
  pl: "Better Auth działa w naszej aplikacji, bez dodatkowej hostowanej usługi logowania. Sesje trwają do 24 godzin. Baza przechowuje identyfikator sesji, powiązane konto, adres IP, informacje o przeglądarce oraz czas utworzenia i wygaśnięcia w celu obsługi logowania i sesji. Możesz je unieważnić w profilu; usunięcie konta usuwa wszystkie sesje. Wygasłe sesje i tymczasowe dane bezpieczeństwa są usuwane codziennie i pozostają do pomyślnego zakończenia czyszczenia. Dane konta pozostają do jego usunięcia. Limity używają identyfikatorów IP lub konta pseudonimizowanych tajnym kluczem oraz tymczasowych liczników. Tokeny Blizzard nie są przechowywane na stałe.",
  ru: "Better Auth работает внутри приложения, без дополнительного внешнего сервиса входа. Сеансы действуют не более 24 часов. Для входа и управления сеансами база хранит идентификатор сеанса, связанный аккаунт, IP-адрес, данные браузера, время создания и истечения. Сеансы можно отозвать в профиле; удаление аккаунта удаляет все сеансы. Истёкшие сеансы и временные данные безопасности очищаются ежедневно и хранятся до успешной очистки. Данные аккаунта хранятся до его удаления. Лимиты используют псевдонимные идентификаторы IP или аккаунта на основе секретного ключа и временные счётчики. Токены Blizzard не сохраняются постоянно.",
};